name: Process hotfix push
on:
  push:
    branches:
      - hotfix
jobs:
  docker-push:
    if: github.ref == 'refs/heads/hotfix'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set time zone to Europe/Berlin
        uses: zcong1993/setup-timezone@master
        with:
          timezone: "Europe/Berlin"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::313329311652:role/PushContainerImagesGithubActions
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build docker image from next and push it
        run: ./.github/workflows/scripts/build_and_push_dev.sh
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: hbt/digitransit-ui
          DOCKER_BASE_TAG: hotfix
