name: Build prod from release
on:
  release:
    types:
      - published
jobs:
  prod-push:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${GITHUB_REF##*/} =~ ^202[0-9][0-1][0-9][0-3][0-9] ]]; then
              echo ::set-output name=match::true
          fi
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::313329311652:role/PushContainerImagesGithubActions
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Push latest image as prod
        if: steps.check-tag.outputs.match == 'true'
        run: ./.github/workflows/scripts/push_prod.sh
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: hbt/digitransit-ui
