apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: sw-staging

images:
  - name: 313329311652.dkr.ecr.eu-central-1.amazonaws.com/hbt/digitransit-ui
    newTag: latest

patchesJson6902:

  - path: patch_deployment.yaml
    target:
      name: otp
      kind: Deployment
      group: apps
      version: .*
